spring.application.name=facimate
server.port=8080

#database
spring.datasource.url=jdbc:mysql://localhost:3307/facimate_db
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.timezone=Asia/Manila

#frontend url
frontend.url=http://localhost:5173

#api integration
teams.webhook.url=${TEAMS_WEBHOOK_URL:https://default7851b4cc2c5c459f96d916731d6b4c.a4.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/af8e7a7f51724975a38da5ac596f5d10/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=2WpU9VejKiYHbex2B_vRs3L9MkdhmIUpdpkxtPVUJB8}